window.movies = [
  { title: "Weapons (2025)", 
    img: "assets/weapons.jpg", 
    desc: "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.", 
    tags: ["Horror", "Supernatural", "Mystery"], 
    spoilers: "Trigger Warnings: Gore, Child Abuse, Substance Abuse <br><br> \"there are absolutely no weapons in this film they lied :(\"- Moji" },
  { title: "Together (2025)", 
    img: "assets/together.jpg", 
    desc: "Years into their relationship, Tim and Millie find themselves at a crossroads as they move to the country. With tensions already flaring, an encounter with an unnatural force threatens to corrupt their lives, their love and their flesh.", 
    tags: ["Body Horror", "Supernatural", "Romance??"], 
    spoilers: "Trigger Warnings: VERY Graphic Body horror, Sexual Content <br><br> \"Dave Franco INSANE FULL HOG\"- Kelly"},
  { title: "Bring Her Back (2025)", 
    img: "assets/bringherback.jpg", 
    desc: "A brother and sister uncover a terrifying ritual at the secluded home of their new foster mother.", 
    tags: ["Horror", "Supernatural"], 
    spoilers: "Trigger Warnings: Gore, Gaslighting <br><br> \"Made my teeth hurt\"- Kelly" },
  { title: "Sinners (2025)", 
    img: "assets/sinners.jpg", 
    desc: "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.", 
    tags: ["Horror", "Supernatural", "Drama"], 
    spoilers: "Trigger Warnings: Child Abuse, Animal Abuse, Excessive Gore, Alcohol Use, Self-Harm, Jumpscares, Sexual Content, RACISM <br><br> \"the sound design and music goes SUPER hard tho would recommend it for that alone\"- Moji" },
  { title: "Until Dawn (2025)", 
    img: "assets/untildawn.jpg", 
    desc: "A group of friends trapped in a time loop, where mysterious foes chase and kill them in gruesome ways, must survive until dawn to escape it.", 
    tags: ["Horror", "Slasher", "Mystery"], 
    spoilers: "Trigger Warnings: Gore, Body Horror, Jumpscares, Self-Harm, Sexual Content" },
  { title: "Oddity (2024)", 
    img: "assets/oddity.jpg", 
    desc: "A psychic medium attempts to uncover the truth behind her sister's murder at the site of the crime.", 
    tags: ["Folk Horror", "Thriller"], 
    spoilers: "Trigger Warnings: Gore but not a lot, Little bit of trypophobia-inducing stuff, some gaslighting <br><br> \"VINDICAAAAATIOOOOOOOON\"- Kelly" },
  { title: "Nosferatu (2024)", 
    img: "assets/nosferatu.jpg", 
    desc: "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.", 
    tags: ["Dark Fantasy", "Horror", "Vampires!!!"], 
    spoilers: "Trigger Warnings: Child Abuse, Gaslight, Substance Use, Animal Abuse, SA, Gore, Body Horror" },
  { title: "The Substance (2024)", 
    img: "assets/thesubstance.jpg", 
    desc: "A fading celebrity takes a black-market drug: a cell-replicating substance that helps her create a younger, better version of herself.", 
    tags: ["Body Horror", "Drama", "Sci-Fi"], 
    spoilers: "Trigger Warnings: Substance Addiction, Excessive Gore, Some Jumpscares, Self-Harm, Nudity" },
  { title: "Primitive Wars (2025)", 
    img: "assets/primitivewar.jpg", 
    desc: "Vietnam. 1968. A recon unit known as Vulture Squad is sent to an isolated jungle valley to uncover the fate of a missing Green Beret platoon. They soon discover they are not alone.", 
    tags: ["Monster Horror", "Action", "War", "Dinosaurs"], 
    spoilers: "Trigger Warnings: Gore, Flashing Lights, The US Military <br><br> \"it's less horror and a lot more action-y but at least it has BRACHIOSAURUS\"- Moji" },
  { title: "Marshmallow (2025)", 
    img: "assets/marshmallow.jpg", 
    desc: "When a once-fabled campfire tale becomes real, a group of campers uncover a profound secret that questions their very existence.", 
    tags: ["Thriller", "Mystery", "Body Horror"], 
    spoilers: "Trigger Warnings: Sexual Content, Child Violence <br><br> \"My favorite marshmallow flavor is chocolate. Especially the ones that are like, mallows but inside them are tiny chocolates that melt in your mouth. Those are *the best*. Oh, the movie? That's like an 8, pretty good.\"- Moji" },
  { title: "Final Destination: Bloodlines (2025)", 
    img: "assets/finaldestination.jpg", 
    desc: "Plagued by a recurring violent nightmare, a college student returns home to find the one person who can break the cycle and save her family from the horrific fate that inevitably awaits them.", 
    tags: ["Horror", "Dark Comedy", "Supernatural"], 
    spoilers: "Trigger Warnings: Excessive Gore, Implied Child Death, Jumspcare-esque scenes, Tongue Piercing <br><br> \"In for a penny, in for a pound.\"- Moji" },
  { title: "Hold Your Breath (2024)", 
    img: "assets/holdyourbreath.jpg", 
    desc: "In 1930s Oklahoma amid the region's horrific dust storms, a woman is convinced that a sinister presence is threatening her family.", 
    tags: ["Horror", "Psychological"], 
    spoilers: "Trigger Warnings: Child abuse, just a liiiittle bit of gore <br><br> \"Goddammit Sarah Paulson you've done it again!!\"- Kelly" },
  { title: "The Spookmaster (2025)", 
    img: "assets/jack.jpg", 
    desc: "The most handsome and beautiful ghastly creature of the hallowed eves. They love long walks on the beach, and trick or treating.", 
    tags: ["Romance", "Comedy", "Spooky"], 
    spoilers: "Trigger Warnings: None! <br><br> \"Omg, you've chosen me!!! Yes, please vote for me in the list!!\" - The Spookmaster <br><br> P.S. You cannot vote for The Spookmaster (2025). <div class=\"jackenstein\"></div>"},
  // { title: "Movie 13", 
  //   img: "assets/jack.png", 
  //   desc: "Description for Movie 13.", 
  //   tags: ["Thriller"], 
  //   spoilers: "spoiler here" },
  // { title: "Movie 14", 
  //   img: "assets/jack.png", 
  //   desc: "Description for Movie 14.", 
  //   tags: ["Horror"], 
  //   spoilers: "spoiler here" },
  // { title: "Movie 15", 
  //   img: "assets/jack.png", 
  //   desc: "Description for Movie 15.", 
  //   tags: ["Action", "Sci-Fi"], 
  //   spoilers: "spoiler here" }
];
