window.movies = [
  { title: "Weapons (2025)", 
    img: "assets/weapons.jpg", 
    desc: "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.", 
    tags: ["Horror", "Supernatural", "Mystery"], 
    spoilers: "Trigger Warnings: Gore, Child Abuse, Substance <br><br> \"there are absolutely no weapons in this film they lied :(\"- Moji" },
  { title: "Together (2025)", 
    img: "assets/together.jpg", 
    desc: "Years into their relationship, Tim and Millie find themselves at a crossroads as they move to the country. With tensions already flaring, an encounter with an unnatural force threatens to corrupt their lives, their love and their flesh.", 
    tags: ["Body Horror", "Supernatural", "Romance??"], 
    spoilers: "Trigger Warnings: VERY Graphic Body horror, Sexual Content <br><br> \"PEENAR SHOWED\"- Kelly"},
  { title: "Movie 3", 
    img: "assets/jack.png", 
    desc: "Description for Movie 3.", 
    tags: ["Comedy", "Family"], 
    spoilers: "spoiler here" },
  { title: "Movie 4", 
    img: "assets/jack.png", 
    desc: "Description for Movie 4.", 
    tags: ["Horror", "Supernatural"], 
    spoilers: "spoiler here" },
  { title: "Movie 5", 
    img: "assets/jack.png", 
    desc: "Description for Movie 5.", 
    tags: ["Sci-Fi", "Adventure"], 
    spoilers: "spoiler here" },
  { title: "Movie 6", 
    img: "assets/jack.png", 
    desc: "Description for Movie 6.", 
    tags: ["Mystery", "Crime"], 
    spoilers: "spoiler here" },
  { title: "Movie 7", 
    img: "assets/jack.png", 
    desc: "Description for Movie 7.", 
    tags: ["Fantasy", "Epic"], 
    spoilers: "spoiler here" },
  { title: "Movie 8", 
    img: "assets/jack.png", 
    desc: "Description for Movie 8.", 
    tags: ["Animation", "Kids"], 
    spoilers: "spoiler here" },
  { title: "Movie 9", 
    img: "assets/jack.png", 
    desc: "Description for Movie 9.", 
    tags: ["Documentary"], 
    spoilers: "spoiler here" },
  { title: "Movie 10", 
    img: "assets/jack.png", 
    desc: "Description for Movie 10.", 
    tags: ["Action", "Adventure"], 
    spoilers: "spoiler here" },
  { title: "Movie 11", 
    img: "assets/jack.png", 
    desc: "Description for Movie 11.", 
    tags: ["Drama"], 
    spoilers: "spoiler here" },
  { title: "Movie 12", 
    img: "assets/jack.png", 
    desc: "Description for Movie 12.", 
    tags: ["Romance", "Comedy"], 
    spoilers: "spoiler here" },
  // { title: "Movie 13", 
  //   img: "assets/jack.png", 
  //   desc: "Description for Movie 13.", 
  //   tags: ["Thriller"], 
  //   spoilers: "spoiler here" },
  // { title: "Movie 14", 
  //   img: "assets/jack.png", 
  //   desc: "Description for Movie 14.", 
  //   tags: ["Horror"], 
  //   spoilers: "spoiler here" },
  // { title: "Movie 15", 
  //   img: "assets/jack.png", 
  //   desc: "Description for Movie 15.", 
  //   tags: ["Action", "Sci-Fi"], 
  //   spoilers: "spoiler here" }
];
